<h2><b>Learn NumPy</b></h2>

<h4><b>Checking the Dimensionality of an Array</b></h4>

In [ ]:
#1D array (ndim=1) → A single list-like structure [1, 2, 3]
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array shape:", arr1.shape, "| Dimensions:", arr1.ndim)

1D Array shape: (5,) | Dimensions: 1


In [ ]:
#2D array (ndim=2) → A matrix or table-like structure [[1, 2], [3, 4]]
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array shape:", arr2.shape, "| Dimensions:", arr2.ndim)

2D Array shape: (2, 3) | Dimensions: 2


In [ ]:
#3D array (ndim=3) → A cube-like structure, often used in images or volumetric data [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array shape:", arr3.shape, "| Dimensions:", arr3.ndim)

3D Array shape: (2, 2, 2) | Dimensions: 3


<h3><b>NumPy Array Operations</b></h3>

In [12]:
import numpy as np

In [13]:
#Arrays
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [14]:
#Addition
add_result = arr1 + arr2
add_result

array([11, 22, 33, 44])

In [15]:
#Subtraction
sub_result = arr1 - arr2
sub_result

array([ 9, 18, 27, 36])

In [16]:
#Multiplication
multi_result = arr1 * arr2
multi_result

array([ 10,  40,  90, 160])

In [21]:
#Division
div_result = arr1 / arr2
div_result

array([10., 10., 10., 10.])

<h3><b>Scalar Operations</b></h3>

In [18]:
scalar = 2

In [19]:
print("Scalar Addition", arr1 + scalar)

Scalar Addition [12 22 32 42]


In [22]:
print("Scalar Subtraction", arr1 - scalar)

Scalar Subtraction [ 8 18 28 38]


In [23]:
print("Scalar Multiplication", arr1 * scalar)

Scalar Multiplication [20 40 60 80]


In [24]:
print("Scalar Division", arr1 / scalar)

Scalar Division [ 5. 10. 15. 20.]


<h3><b>Matrix Operations</b></h3>

<h4>Even if these operations are to be performed on 2D arrays (matrices), the syntax will remain the same.</h4>

In [25]:
#Arrays
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

In [26]:
print("Matrix Addition", mat1 + mat2)

Matrix Addition [[ 6  8]
 [10 12]]


In [33]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)
